name: openchance
description: OpenChance - Connect Challengers with Solvers
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.0
  riverpod: ^2.4.0
  riverpod_generator: ^2.3.0

  # API & Networking
  dio: ^5.3.0
  retrofit: ^4.0.0
  json_serializable: ^6.7.0

  # Authentication
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0

  # UI & Design
  flutter_svg: ^2.0.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.4.0
  intl: ^0.19.0

  # Navigation
  go_router: ^11.0.0

  # Local Storage
  hive: ^2.2.0
  hive_flutter: ^1.1.0

  # Real-time
  web_socket_channel: ^2.4.0

  # Payments
  stripe_flutter: ^10.0.0

  # Analytics
  firebase_core: ^2.24.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.0

  # Notifications
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^16.1.0

  # Utilities
  logger: ^2.0.0
  connectivity_plus: ^5.0.0
  package_info_plus: ^5.0.0
  url_launcher: ^6.1.0
  share_plus: ^7.2.0
  permission_handler: ^11.4.0

  # Image Handling
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  video_player: ^2.8.0

  # Localization
  easy_localization: ^3.0.0

  # Testing
  mockito: ^5.4.0
  http_mock_adapter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  retrofit_generator: ^7.0.0
  hive_generator: ^2.0.0
  riverpod_generator: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

